### ISSUE TITLE
Elliptical curve cryptography option for HTTPS

### ISSUE THREAD

**Issue by chrisericchapman** [demonsaw/demonsaw#23]
for the apparent sniffed HTTPS objects it would be nice to wrap your stuff behind an additional layer of ECC elliptical curve cryptography )

**Comment by ghost** [comment]
HTTPS? Demonsaw doesn't use https and even the entropy sources don't yet use https (3.2.0 release hopefully.)
What kind of 'stuff' are you wanting to prevent sniffing that demonsaw doesn't already protect?
