### ISSUE TITLE
Complete Acquisition of All Social Website Functions

### ISSUE THREAD

**Issue by HFisher1212** [demonsaw/demonsaw#25]
Create shared file templates of current social websites (ie. FB, SC, IG, TW,  em, etc) in order to provide same functionality.  The idea here is if you make it easy for the average user to host their own facsimile of these pages they would not need the latter with their limitations, personal data mining, and security threats.  This would eliminate required user knowledge of creation while providing greater control over user content.  Users could effortlessly transition to a personal hosting platforms (such as rasp pi) to provide sharing and a singular acquisition and storage location.  Demonsaw would provide security for all transactions.

**Comment by ghost** [comment]
Need more explanation. Are you looking for demonsaw to become a social platform or use it as a proxy connection or layer over social sites? Or are you wanting demonsaw to become like ZeroNet?

**Comment by HFisher1212** [comment]
Yes, a ultra secure P2P social platform but not dark and decentralized like ZeroNet.  Core assets would be- providing easy installation of portal pages and open source functionalities (such as OwnCloud, etc) for novice users, extremely limited personal public data, and superior security and access privileges.  While layering would appear useful, I am worried that any public footprint would cause it's presents to be too visible.  I simply feel personal data should not be under the control, scrutiny, and constraints of corporations that themselves are under constant threat of internal integrity and external attack.

**Comment by Olivered** [comment]
This would require a lot of work and would significantly distract from the core scope of demonsaw.
[https://en.wikipedia.org/wiki/Feature_creep](https://en.wikipedia.org/wiki/Feature_creep)
Demonsaw is dark and decentralized. That is pretty much what makes it secure.
What you are asking for is essentially drupal.
