### ISSUE TITLE
CLI Support in 3.x?

### ISSUE THREAD

**Issue by NoraCodes** [demonsaw/demonsaw#26]
There is no CLI support in 3.x, and without CLI support Demonsaw is useless for my primary use case. Is it planned?

**Comment by eijah** [comment]
launches tonight :) 
On Oct 2, 2016 3:26 PM, Leo Tindall notifications@github.com wrote:There is no CLI support in 3.x, and without CLI support Demonsaw is useless for my primary use case. Is it planned?

**Comment by NoraCodes** [comment]
Well, perfect! Thanks very much, Eijah.
