### ISSUE TITLE
3_core building: «./security/hash/hmac.h:147:61: error: ‘const class CryptoPP::HMAC<CryptoPP::SHA256>’ has no member named ‘empty’»

### ISSUE THREAD

**Issue by Geremia** [demonsaw/demonsaw#44]
When building 3_core on Linux, I get this error:
```
./security/hash/hmac.h:147:61: error: ‘const class CryptoPP::HMAC<CryptoPP::SHA256>’ has no member named ‘empty’
   virtual bool has_key() const override { return !m_routine.empty(); }
                                                   ~~~~~~~~~~^~~~~
```

**Comment by eijah** [comment]
I think I modified the cryptopp code and added the empty() function. You can probably just comment that function out and it will build.

**Comment by eijah** [comment]
Since it's virtual override you'll probably need to have it return false or modify the entire inheritance hierarchy.  Your other option is to modify the cryptopp library and add the empty() function to m_routine
